### ISSUE TITLE
Better name

### ISSUE THREAD

**Issue by gig745** [Sitback/helm#1]
How about dockup?

**Comment by chinthakagodawita** [comment]
Might be a bit too repetitive: `dockup up` :smile: 

Current contenders:
- `fez`
- `rigger`

**Comment by gig745** [comment]
Still more names:
- literal
  soe
- seed
  sprout
  bud
  shoot
  sow
- parts of a boat
  anchor
  jibe
  jib
  cog
  helm
  skeg
  spar
  hank
- boats
  yawl
  ferry

**Comment by mlhoque** [comment]
I like "helm" :)

**Comment by chinthakagodawita** [comment]
I do like `helm` too but there's a few out there already:
- https://github.com/emacs-helm/helm
- https://github.com/switchface/helm

**Comment by chinthakagodawita** [comment]
`kepi`?

http://dictionary.reference.com/browse/kepi

**Comment by mlhoque** [comment]
https://github.com/jcast/kepi
https://github.com/the-domains/kepi

:)

**Comment by chinthakagodawita** [comment]
Ha, good point.

:+1: to `helm` 

@jrhodes-sitback ?

**Comment by gig745** [comment]
Good with me .. it's root meaning is found in 'helve' - the handle of a
tool or weapon

On Tue, Nov 17, 2015 at 10:55 AM, Chin Godawita notifications@github.com
wrote:

> Ha, good point.
> 
> [image: :+1:] to helm
> 
> @jrhodes-sitback https://github.com/jrhodes-sitback ?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/Sitback/docker-hat-v2/issues/1#issuecomment-157212648
> .

## 

Jonathan Rhodes | Senior Drupal Developer

## 

 39 - 41 Lower Fort Street, The Rocks, Sydney. 2000
https://www.facebook.com/pages/Sitback/159057074134649  
https://twitter.com/Sitback  
http://www.linkedin.com/company/1482531?trk=tyah&trkInfo=tarId%3A1413439096225%2Ctas%3ASitback%2Cidx%3A2-1-4
http://www.sitback.com.au

**Comment by chinthakagodawita** [comment]
Consensus! `helm` it is.

I'll rename the repository when I get the chance.

**Comment by chinthakagodawita** [comment]
Repository renamed, Travis renamed and all code rebranded.
